//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_PP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostOfWork
    {
        public int ID { get; set; }
        public int IdIssueEquipment { get; set; }
        public string Name { get; set; }
        public int Cost { get; set; }
    
        public virtual IssueEquipment IssueEquipment { get; set; }
    }
}
