//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_PP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginedTable
    {
        public int ID { get; set; }
        public string LoginUser { get; set; }
        public int PasswordUser { get; set; }
        public int IdRole { get; set; }
    
        public virtual RoleTable RoleTable { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
