//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_PP.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Knyazeva_PP_Entities : DbContext
    {
        public Knyazeva_PP_Entities()
            : base("name=Knyazeva_PP_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AcceptEquipment> AcceptEquipment { get; set; }
        public virtual DbSet<ClientTable> ClientTable { get; set; }
        public virtual DbSet<CostOfWork> CostOfWork { get; set; }
        public virtual DbSet<EquipmentInRepair> EquipmentInRepair { get; set; }
        public virtual DbSet<EquipmentTable> EquipmentTable { get; set; }
        public virtual DbSet<IssueEquipment> IssueEquipment { get; set; }
        public virtual DbSet<LoginedTable> LoginedTable { get; set; }
        public virtual DbSet<OrderSpareParts> OrderSpareParts { get; set; }
        public virtual DbSet<OrderTable> OrderTable { get; set; }
        public virtual DbSet<RoleTable> RoleTable { get; set; }
        public virtual DbSet<StatusTable> StatusTable { get; set; }
        public virtual DbSet<TypeOrderTable> TypeOrderTable { get; set; }
        public virtual DbSet<UserTable> UserTable { get; set; }
    }
}
