//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_PP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderTable()
        {
            this.OrderSpareParts = new HashSet<OrderSpareParts>();
        }
    
        public int ID { get; set; }
        public int IdClient { get; set; }
        public int IdEquipment { get; set; }
        public string Damage { get; set; }
        public System.DateTime DateOrder { get; set; }
        public int TypeOrder { get; set; }
    
        public virtual AcceptEquipment AcceptEquipment { get; set; }
        public virtual ClientTable ClientTable { get; set; }
        public virtual EquipmentInRepair EquipmentInRepair { get; set; }
        public virtual EquipmentTable EquipmentTable { get; set; }
        public virtual IssueEquipment IssueEquipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderSpareParts> OrderSpareParts { get; set; }
        public virtual TypeOrderTable TypeOrderTable { get; set; }
    }
}
