//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_PP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderSpareParts
    {
        public int ID { get; set; }
        public int IdOrder { get; set; }
        public string Name { get; set; }
        public string Link { get; set; }
        public int Quantity { get; set; }
        public string Description { get; set; }
        public int IdStatus { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual StatusTable StatusTable { get; set; }
        public virtual OrderTable OrderTable { get; set; }
    }
}
